# Generated by Django 5.0.6 on 2024-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('composition', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('kilocalories', models.IntegerField()),
            ],
        ),
    ]
